//-------------------------------------------------------------------
// Program:  Homework #2: Roshambo
// Programmer:  Joseph Cunningham
// Class: Engr 50 TTH Section 1
// Date:  9/12/15
//
// The program is a game of Roshambo.  The game will welcome the 
// player and explain the rules.  It will then prompt the user for a 
// number from 1-3 standing for Rock, Paper or Scissors.  It will 
// then declare a winner and play again till the player decided to 
// quit
//-------------------------------------------------------------------

#include<stdio.h> // For input output
#include<stdlib.h>  // For rand & srand functions
#include<time.h>  // For time function to initialize srand

int main(void)
{
	// Variable declarations

	int input;  // Player input
	int output;  // scanf return value for input check
	int computer;  // random number generated by computer
	int again = 1; // Sentinel value for while loop

	// Initialization of random number generator

	srand(time(NULL));

	while(again == 1)
	{
		
		// Print instructions and prompt user for input

		printf("\nWelcome to Roshambo!\n");
		printf("\n");
		printf("Press 1 to play Rock.\n");
		printf("Press 2 to play Paper.\n");
		printf("Press 3 to play Scissors.\n");
		printf("Press other keys to quit.\n");
		printf("\nRoshambo!  You choose: ");
		output = scanf("%d", &input);

		// Player types a character

		if(output != 1)
		{
			fflush(stdin);
			printf("Thank you for playing!  Goodbye!\n");
			again = 0;
		}

		//  Player chooses Rock (1)

		else if(input == 1)
		{

			computer = rand() % 3 + 1;
			printf ("\nYou choose Rock\n");

			// What did the computer get?

			// Computer is 1

			if(computer == 1)
			{
				printf("I got Rock! We tied!\n");
			}

			// Computer is 2
			else if(computer == 2)
			{
				printf("I got paper! I WIN!\n");
			}

			// Computer is 3

			else
			{
				printf("I got Scissors!  You won!\n");
			}
		}

		// Player chooses Paper (2)

		else if(input == 2)
		{
			computer = rand() % 3 + 1;
			printf("\nYou chose Paper\n");

			// What did the computer get?

			// Computer got 1

			if(computer == 1)
			{
				printf("I got Rock!  You won!\n");
			}

			// Computer got 2

			else if(computer == 2)
			{
				printf("I got Paper!  We tied!\n");
			}

			// Computer is 3

			else
			{
				printf("I got Scissors!  I won!\n");
			}
		}

		// Player chose Scissors(3)

		else if(input == 3)
		{
			computer = rand() % 3 + 1;
			printf("\nYou chose Scissors\n");

			// What did the computer get?

			// Computer got 1

			if(computer == 1)
			{
				printf("I got Rock!  I won\n");
			}

			// Computer got 2

			else if(computer == 2)
			{
				printf("I got Paper!  You won!\n");
			}

			// Computer got 3

			else
			{
				printf("I got Scissors! We tied!\n");
			}
		}
		
		// Player input a number above 3

		else
		{
			printf("\nThank you for playing!  Goodbye!\n");
			again = 0;
		}
	}

	return 0;
}
